<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML DIR="LTR"><HEAD>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=gb2312">
<TITLE>异常抛出，但无法抓住</TITLE>
<!--CSS_START-->
<SCRIPT SRC="../scripts/vs70.js"></SCRIPT>
<SCRIPT SRC="../scripts/vs70link.js"></SCRIPT>
<!--CSS_END--></HEAD>
<body topmargin=0 id="bodyID" class = "dtBODY">

<!--NONSCROLLING BANNER START-->
<div id="nsbanner">
<div id="bannerrow1">
<TABLE CLASS="bannerparthead" CELLSPACING=0>
<TR ID="hdr">
<TD CLASS="runninghead" nowrap>JScript</TD>
<TD CLASS="product" nowrap>&nbsp;</TD>
</TR>
</TABLE>
</div>
<div id="TitleRow">
<H1 class="dtH1"><A NAME="js56jserrexceptionthrownnotcaught"></A>异常抛出，但无法抓住</H1>
</div></div>
<!--NONSCROLLING BANNER END-->
<DIV id="nstext" valign="bottom">
<P>在代码中包括了一条 <B>throw</B> 语句，但没有将其包含在某个 <B>try</B> 语句块内，或者没有相关的 <B>catch</B> 语句块来捕获错误。异常是在 <B>try </B>语句块中使用 <B>throw </B>语句被抛出，并且应该由 <B>try </B>语句块外的 <B>catch </B>语句抓住。</P>

<P class="labelproc"><B>要改正此错误</B>

<UL type="disc">
	<LI>用 <B>try </B>语句块将可能产生异常的代码封住，并确保外面有一个相应的 <B>catch</B> 语句块。</li>

	<LI>确认 catch 语句中为正确的异常格式。</li>

	<LI>如果异常被再次抛出，确认存在相应的 catch 语句。</li>
</UL>

<H4 class="dtH4">请参阅</H4>

<P><A HREF="js56jsobjerror.htm">Error 对象</A> | <A HREF="js56jsstmthrow.htm">throw 语句</A> | <A HREF="js56jsstmtrycatch.htm">try...catch 语句</A></P>
<!--Footer Start-->
<DIV CLASS="footer">
<br>
<HR><!--Copyright-->
<p>&copy; 2001 Microsoft Corporation. 保留所有权利。</p></div> <!--Closes the footer div-->
</div> <!--closes the topic content div-->
<!--FOOTER_END-->
</BODY>
</HTML>
